// Auto-generated by @sfdc-recorder/codegen.
// Source recording: salesforce-testing (2026-05-07T10:50:58.171Z)
// Salesforce context: unknown
// Steps: 5

import { test, expect } from '@playwright/test';
import { waitForSalesforce } from '@sfdc-recorder/runner/waits';

test("salesforce-testing", async ({ page }) => {
  await page.goto("https://lplone--qa.sandbox.lightning.force.com/lightning/o/Account/list?filterName=__Recent");
  await waitForSalesforce(page);

  // Step 1: navigate to https://lplone--qa.sandbox.lightning.force.com/lightning/o/Account/list?filterName=__Recent
  await page.goto("https://lplone--qa.sandbox.lightning.force.com/lightning/o/Account/list?filterName=__Recent");
  await waitForSalesforce(page);

  // Step 2: navigate to https://lplone--qa.sandbox.lightning.force.com/lightning/o/Opportunity/home
  await page.goto("https://lplone--qa.sandbox.lightning.force.com/lightning/o/Opportunity/home");
  await waitForSalesforce(page);

  // Step 3: navigate to https://lplone--qa.sandbox.lightning.force.com/lightning/o/Opportunity/list
  await page.goto("https://lplone--qa.sandbox.lightning.force.com/lightning/o/Opportunity/list");
  await waitForSalesforce(page);

  // Step 4: navigate to https://lplone--qa.sandbox.lightning.force.com/lightning/o/Opportunity/list?filterName=__Recent
  await page.goto("https://lplone--qa.sandbox.lightning.force.com/lightning/o/Opportunity/list?filterName=__Recent");
  await waitForSalesforce(page);

  // Step 5: navigate to https://lplone--qa.sandbox.lightning.force.com/lightning/o/Opportunity/list?filterName=PRU_Sourced_Candidate_List
  await page.goto("https://lplone--qa.sandbox.lightning.force.com/lightning/o/Opportunity/list?filterName=PRU_Sourced_Candidate_List");
  await waitForSalesforce(page);

});
