import type { ElementSnapshot, FramePathSegment } from '@sfdc-recorder/locator-engine';
import type {
  CodegenOptions,
  Recording,
  RecordedAction,
  RecordingStep,
} from './types.js';

const DEFAULT_OPTS: Required<CodegenOptions> = {
  testName: 'recordedFlow',
  includeFallbackHints: true,
  insertSalesforceWaits: true,
  emitGroupsAsFunctions: true,
  parameterizeFixtures: false,
};

/**
 * Generate a Playwright TypeScript spec from a Recording.
 *
 * v2 features:
 *  - frameLocator() chains for iframes
 *  - Salesforce field helpers (selectPicklistOption, selectLookupRecord, etc.)
 *  - assertion steps emit expect(...)
 *  - groups emit as named functions
 *  - $VAR placeholders surface as fixture parameters
 */
export function generateSpec(recording: Recording, options: CodegenOptions = {}): string {
  const opts = { ...DEFAULT_OPTS, ...options };
  const lines: string[] = [];

  lines.push(`// Auto-generated by @sfdc-recorder/codegen.`);
  lines.push(`// Source recording: ${recording.name} (${recording.createdAt})`);
  lines.push(`// Salesforce context: ${recording.context}`);
  lines.push(`// Steps: ${recording.steps.length}${recording.groups?.length ? `, groups: ${recording.groups.length}` : ''}`);
  lines.push(``);

  // Imports
  const imports = new Set<string>();
  const helpers = collectHelpers(recording);
  imports.add(`import { test, expect, type Page, type FrameLocator } from '@playwright/test';`);
  if (opts.insertSalesforceWaits) {
    imports.add(`import { waitForSalesforce, waitForToast, waitForModalOpen, waitForModalClose } from '@sfdc-recorder/runner/waits';`);
  }
  if (helpers.size > 0) {
    imports.add(`import { ${[...helpers].sort().join(', ')} } from '@sfdc-recorder/runner/sfdcFields';`);
  }
  for (const i of imports) lines.push(i);
  lines.push(``);

  // Fixture type if parameterized
  if (opts.parameterizeFixtures && recording.variables && recording.variables.length > 0) {
    lines.push(`export interface Fixture {`);
    for (const v of recording.variables) lines.push(`  ${v}: string;`);
    lines.push(`}`);
    lines.push(``);
  }

  // Group helpers (sub-flows)
  const groupedSteps = groupSteps(recording);
  const ungroupedTopLevel: typeof groupedSteps.ungrouped = groupedSteps.ungrouped;

  if (opts.emitGroupsAsFunctions) {
    for (const g of recording.groups ?? []) {
      const groupSteps = groupedSteps.byGroupId.get(g.id) ?? [];
      if (groupSteps.length === 0) continue;
      emitGroupFunction(lines, g.name, g.description, groupSteps, opts);
      lines.push(``);
    }
  }

  // Test wrapper
  const fixtureParam = opts.parameterizeFixtures && recording.variables?.length ? `, fixture: Fixture` : '';
  const declParam = fixtureParam ? `async ({ page }${fixtureParam.replace(', ', ', ')}) =>` : `async ({ page }) =>`;
  lines.push(`test(${JSON.stringify(recording.name)}, ${declParam} {`);

  if (recording.startUrl) {
    lines.push(`  await page.goto(${JSON.stringify(recording.startUrl)});`);
    if (opts.insertSalesforceWaits) lines.push(`  await waitForSalesforce(page);`);
    lines.push(``);
  }

  // Emit ungrouped steps inline; for groups, emit a function call.
  let stepCounter = 0;
  for (const block of orderedBlocks(recording, groupedSteps)) {
    if (block.type === 'group') {
      lines.push(`  // group: ${block.group.name}`);
      const callArg = opts.parameterizeFixtures && recording.variables?.length ? 'page, fixture' : 'page';
      lines.push(`  await ${functionNameFor(block.group.name)}(${callArg});`);
      lines.push(``);
    } else {
      stepCounter++;
      emitStep(lines, block.step, stepCounter, opts, '  ');
    }
  }
  // Suppress unused-variable warnings if parameterized but no variables actually consumed:
  if (ungroupedTopLevel.length === 0 && (recording.steps.length === 0)) {
    lines.push(`  // recording has no top-level steps`);
  }

  lines.push(`});`);
  lines.push(``);
  return lines.join('\n');
}

interface GroupedSteps {
  byGroupId: Map<string, RecordingStep[]>;
  ungrouped: RecordingStep[];
}

function groupSteps(recording: Recording): GroupedSteps {
  const byGroupId = new Map<string, RecordingStep[]>();
  const ungrouped: RecordingStep[] = [];
  for (const s of recording.steps) {
    if (s.groupId) {
      const list = byGroupId.get(s.groupId) ?? [];
      list.push(s);
      byGroupId.set(s.groupId, list);
    } else {
      ungrouped.push(s);
    }
  }
  return { byGroupId, ungrouped };
}

type OrderedBlock =
  | { type: 'step'; step: RecordingStep }
  | { type: 'group'; group: { id: string; name: string } };

/**
 * Walk the steps in original order. The first time we see a step belonging
 * to a group, emit a single "group call" placeholder; subsequent group steps
 * are absorbed by that placeholder.
 */
function orderedBlocks(recording: Recording, grouped: GroupedSteps): OrderedBlock[] {
  const seenGroups = new Set<string>();
  const out: OrderedBlock[] = [];
  for (const step of recording.steps) {
    if (step.groupId) {
      if (!seenGroups.has(step.groupId)) {
        const g = recording.groups?.find((x) => x.id === step.groupId);
        if (g) {
          out.push({ type: 'group', group: { id: g.id, name: g.name } });
          seenGroups.add(step.groupId);
        }
      }
      // skip — emitted by the group function
    } else {
      out.push({ type: 'step', step });
    }
  }
  return out;
}

function emitGroupFunction(
  lines: string[],
  name: string,
  description: string | undefined,
  steps: RecordingStep[],
  opts: Required<CodegenOptions>,
): void {
  if (description) lines.push(`/** ${description} */`);
  const fnName = functionNameFor(name);
  const fixtureParam = opts.parameterizeFixtures ? ', fixture: Fixture' : '';
  lines.push(`async function ${fnName}(page: Page${fixtureParam}): Promise<void> {`);
  let n = 0;
  for (const step of steps) {
    n++;
    emitStep(lines, step, n, opts, '  ');
  }
  lines.push(`}`);
}

function emitStep(
  out: string[],
  step: RecordingStep,
  num: number,
  opts: Required<CodegenOptions>,
  indent: string,
): void {
  out.push(`${indent}// Step ${num}: ${humanize(step.action)}`);
  if (step.comment) out.push(`${indent}// ${step.comment}`);

  const fix = (v: string) => stringLiteralWithFixtures(v, opts.parameterizeFixtures);

  switch (step.action.type) {
    case 'click':
      out.push(`${indent}await ${pageExpr(step.action.snapshot)}.click();`);
      maybeFallbacks(out, step.action.snapshot, opts, indent);
      maybeWaitForModalIfHinted(out, step, indent, opts);
      break;
    case 'dblclick':
      out.push(`${indent}await ${pageExpr(step.action.snapshot)}.dblclick();`);
      maybeFallbacks(out, step.action.snapshot, opts, indent);
      break;
    case 'input':
    case 'change':
      out.push(`${indent}await ${pageExpr(step.action.snapshot)}.fill(${fix(step.action.value)});`);
      maybeFallbacks(out, step.action.snapshot, opts, indent);
      break;
    case 'select':
      out.push(`${indent}await ${pageExpr(step.action.snapshot)}.selectOption(${fix(step.action.value)});`);
      maybeFallbacks(out, step.action.snapshot, opts, indent);
      break;
    case 'press':
      out.push(`${indent}await ${pageExpr(step.action.snapshot)}.press(${JSON.stringify(step.action.key)});`);
      break;
    case 'navigate':
      out.push(`${indent}await page.goto(${JSON.stringify(step.action.url)});`);
      if (opts.insertSalesforceWaits) out.push(`${indent}await waitForSalesforce(page);`);
      break;
    case 'waitFor':
      out.push(`${indent}// wait reason: ${step.action.reason}`);
      out.push(`${indent}await page.waitForLoadState('networkidle');`);
      break;
    case 'picklist':
      out.push(`${indent}await selectPicklistOption(${pageExpr(step.action.snapshot)}, ${fix(step.action.optionLabel)});`);
      break;
    case 'multipicklist':
      out.push(
        `${indent}await selectMultiPicklist(${pageExpr(step.action.snapshot)}, [${step.action.optionLabels.map(fix).join(', ')}]);`,
      );
      break;
    case 'lookup':
      out.push(
        `${indent}await selectLookupRecord(${pageExpr(step.action.snapshot)}, ${fix(step.action.searchText)}, ${fix(step.action.selectedRecord)});`,
      );
      break;
    case 'combobox':
      out.push(`${indent}await selectComboboxOption(${pageExpr(step.action.snapshot)}, ${fix(step.action.optionLabel)});`);
      break;
    case 'date':
      out.push(`${indent}await setDateValue(${pageExpr(step.action.snapshot)}, ${fix(step.action.isoValue)});`);
      break;
    case 'datetime':
      out.push(`${indent}await setDateTimeValue(${pageExpr(step.action.snapshot)}, ${fix(step.action.isoValue)});`);
      break;
    case 'checkbox':
      out.push(`${indent}await setCheckboxState(${pageExpr(step.action.snapshot)}, ${step.action.checked});`);
      break;
    case 'fileUpload':
      out.push(
        `${indent}await ${pageExpr(step.action.snapshot)}.setInputFiles([${step.action.filePaths.map((p) => JSON.stringify(p)).join(', ')}]);`,
      );
      break;
    case 'assertVisible':
      out.push(`${indent}await expect(${pageExpr(step.action.snapshot)}).toBeVisible();`);
      break;
    case 'assertHidden':
      out.push(`${indent}await expect(${pageExpr(step.action.snapshot)}).toBeHidden();`);
      break;
    case 'assertText': {
      const exp = fix(step.action.expected);
      const matcher = step.action.match ?? 'exact';
      const call =
        matcher === 'contains'
          ? `toContainText(${exp})`
          : matcher === 'regex'
            ? `toHaveText(new RegExp(${exp}))`
            : `toHaveText(${exp})`;
      out.push(`${indent}await expect(${pageExpr(step.action.snapshot)}).${call};`);
      break;
    }
    case 'assertValue':
      out.push(`${indent}await expect(${pageExpr(step.action.snapshot)}).toHaveValue(${fix(step.action.expected)});`);
      break;
    case 'assertUrl': {
      const exp = fix(step.action.expected);
      const matcher = step.action.match ?? 'contains';
      const call =
        matcher === 'exact'
          ? `toBe(${exp})`
          : matcher === 'regex'
            ? `toMatch(new RegExp(${exp}))`
            : `toContain(${exp})`;
      out.push(`${indent}expect(page.url()).${call};`);
      break;
    }
    case 'assertToast': {
      const args: string[] = [];
      if (step.action.text) args.push(`text: ${fix(step.action.text)}`);
      if (step.action.variant) args.push(`variant: ${JSON.stringify(step.action.variant)}`);
      out.push(`${indent}await waitForToast(page${args.length ? `, { ${args.join(', ')} }` : ''});`);
      break;
    }
  }
  out.push(``);
}

function maybeWaitForModalIfHinted(
  out: string[],
  step: RecordingStep,
  indent: string,
  opts: Required<CodegenOptions>,
): void {
  if (!opts.insertSalesforceWaits) return;
  const c = step.comment?.toLowerCase() ?? '';
  if (c.includes('opens modal')) out.push(`${indent}await waitForModalOpen(page);`);
  if (c.includes('closes modal')) out.push(`${indent}await waitForModalClose(page);`);
}

function pageExpr(snapshot: ElementSnapshot): string {
  const top = snapshot.candidates[0];
  const scope = renderFrameExpression(snapshot.framePath);
  if (!top) return `${scope}.locator('body')`;
  return `${scope}.${top.playwright}`;
}

function renderFrameExpression(framePath?: FramePathSegment[]): string {
  if (!framePath || framePath.length === 0) return 'page';
  let expr = 'page';
  for (const seg of framePath) {
    expr += `.frameLocator(${JSON.stringify(pickFrameSelector(seg))})`;
  }
  return expr;
}

function pickFrameSelector(seg: FramePathSegment): string {
  if (seg.name) return `iframe[name="${escape(seg.name)}"]`;
  if (seg.selector) return seg.selector;
  if (seg.urlMatch) return `iframe[src*="${escape(seg.urlMatch)}"]`;
  return 'iframe';
}

function escape(value: string): string {
  return value.replace(/"/g, '\\"');
}

function maybeFallbacks(
  out: string[],
  snapshot: ElementSnapshot,
  opts: Required<CodegenOptions>,
  indent: string,
): void {
  if (!opts.includeFallbackHints) return;
  const fallbacks = snapshot.candidates.slice(1, 4);
  if (fallbacks.length === 0) return;
  out.push(`${indent}// fallbacks (decreasing confidence):`);
  for (const fb of fallbacks) {
    out.push(`${indent}//   - page.${fb.playwright}   // ${fb.description}`);
  }
}

function humanize(a: RecordedAction): string {
  switch (a.type) {
    case 'click':
      return `click ${describe(a.snapshot)}`;
    case 'dblclick':
      return `double-click ${describe(a.snapshot)}`;
    case 'input':
      return `type "${truncate(a.value)}" into ${describe(a.snapshot)}`;
    case 'change':
      return `change ${describe(a.snapshot)} to "${truncate(a.value)}"`;
    case 'select':
      return `select "${truncate(a.value)}" from ${describe(a.snapshot)}`;
    case 'press':
      return `press ${a.key}`;
    case 'navigate':
      return `navigate to ${a.url}`;
    case 'waitFor':
      return `wait: ${a.reason}`;
    case 'picklist':
      return `pick "${a.optionLabel}" in ${describe(a.snapshot)}`;
    case 'multipicklist':
      return `multi-pick [${a.optionLabels.join(', ')}] in ${describe(a.snapshot)}`;
    case 'lookup':
      return `lookup "${a.searchText}" → "${a.selectedRecord}"`;
    case 'combobox':
      return `combobox pick "${a.optionLabel}"`;
    case 'date':
      return `date ${a.isoValue}`;
    case 'datetime':
      return `datetime ${a.isoValue}`;
    case 'checkbox':
      return `${a.checked ? 'check' : 'uncheck'} ${describe(a.snapshot)}`;
    case 'fileUpload':
      return `upload ${a.filePaths.length} file(s)`;
    case 'assertVisible':
      return `assert visible: ${describe(a.snapshot)}`;
    case 'assertHidden':
      return `assert hidden: ${describe(a.snapshot)}`;
    case 'assertText':
      return `assert text "${truncate(a.expected)}" on ${describe(a.snapshot)}`;
    case 'assertValue':
      return `assert value "${truncate(a.expected)}" on ${describe(a.snapshot)}`;
    case 'assertUrl':
      return `assert URL ${a.match ?? 'contains'} "${truncate(a.expected)}"`;
    case 'assertToast':
      return `assert toast${a.variant ? ` (${a.variant})` : ''}${a.text ? ` "${truncate(a.text)}"` : ''}`;
  }
}

function describe(snapshot: ElementSnapshot): string {
  return snapshot.candidates[0]?.description ?? `<${snapshot.tagName}>`;
}

function truncate(s: string): string {
  return s.length > 40 ? s.slice(0, 40) + '…' : s;
}

function functionNameFor(groupName: string): string {
  const camel = groupName
    .replace(/[^a-zA-Z0-9 _-]/g, '')
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((w, i) => (i === 0 ? w[0]?.toLowerCase() + w.slice(1) : w[0]?.toUpperCase() + w.slice(1)))
    .join('');
  return camel || 'subFlow';
}

/** Detect which sfdcFields helpers will be referenced in the output. */
function collectHelpers(recording: Recording): Set<string> {
  const helpers = new Set<string>();
  for (const s of recording.steps) {
    switch (s.action.type) {
      case 'picklist':
        helpers.add('selectPicklistOption');
        break;
      case 'multipicklist':
        helpers.add('selectMultiPicklist');
        break;
      case 'lookup':
        helpers.add('selectLookupRecord');
        break;
      case 'combobox':
        helpers.add('selectComboboxOption');
        break;
      case 'date':
        helpers.add('setDateValue');
        break;
      case 'datetime':
        helpers.add('setDateTimeValue');
        break;
      case 'checkbox':
        helpers.add('setCheckboxState');
        break;
    }
  }
  return helpers;
}

/**
 * Convert a recorded value with $VAR placeholders into source code.
 *  - parameterize=false → JSON.stringify(value) (literal)
 *  - parameterize=true  → template literal with `${fixture.VAR}`
 */
function stringLiteralWithFixtures(value: string, parameterize: boolean): string {
  if (!parameterize || !/\$\{?[A-Z_][A-Z0-9_]*\}?/.test(value)) {
    return JSON.stringify(value);
  }
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{?([A-Z_][A-Z0-9_]*)\}?/g, (_m, name: string) => `\${fixture.${name}}`);
  return `\`${escaped}\``;
}
