// Auto-generated by @sfdc-recorder/codegen.
// Source recording: create-account-with-contact (2026-05-07T12:00:00.000Z)
// Salesforce context: lightning
// Steps: 4

import { test, expect } from '@playwright/test';
import { waitForSalesforce } from '@sfdc-recorder/runner/waits';

test('create-account-with-contact', async ({ page }) => {
  await page.goto('https://example.lightning.force.com/lightning/o/Account/list');
  await waitForSalesforce(page);

  // Step 1: click role=button name="New"
  await page.getByRole('button', { name: 'New' }).click();
  // fallbacks (decreasing confidence):
  //   - page.getByText("New", { exact: true })   // visible text "New"

  // Step 2: type "Acme Corp" into field labelled "Account Name"
  await page.getByLabel('Account Name', { exact: true }).fill('Acme Corp');
  // fallbacks (decreasing confidence):
  //   - page.getByRole("textbox", { name: "Account Name" })   // role=textbox name="Account Name"

  // Step 3: select "Customer" from field labelled "Type"
  await page.getByLabel('Type', { exact: true }).selectOption('Customer');

  // Step 4: click role=button name="Save"
  await page.getByRole('button', { name: 'Save' }).click();
});
